

services:
  php:
    build          : ./docker/php/${PHP_VERSION}
    container_name : ${PROJECT_NAME}-php-${PHP_VERSION}
    ports:
      - '${DOCKER_INTERFACE}:${PHP_INTERFACE}'
#    links:
#      - mysql
#      - memcached
    networks:
      - marketes
    volumes:
      - ./docker/logs/php:/var/log/php

    restart        : unless-stopped



networks:
  marketes:
    driver: bridge
